general:
  main_path: ./
  config: SimpleEncoderNextLayer
  experiment: test_experiment
  seed: 42
  mixed_precision: "no"
  batch_size: 10
  test_batch_size: 10
  losses: 
    lambda_thickness: 1.0
  dataset:
    thickness_range: [0, 200]  # in nm
    thickness_steps: 1
    structure_layers: 32
    ranges: [400, 700]
    steps: 1  # hpc 0.1
    dataset_size: 8000
    test_dataset_size: 4
    spectrum_len: 301 # (700-400)/1 + 1
    # num_materials: 2
train:
  num_workers: 16
  save_checkpoints: true
  epochs: 200
  save_every: 2
  clip_max_norm: 1.0
  learning_rate: 0.0001
test:
  num_workers: 16
