general:
  main_path: ./
  config: simple_encoder
  experiment: test_experiment
  seed: 42
  mixed_precision: "no"
  batch_size: 150
  test_batch_size: 150
  losses: 
    lambda_thickness: 1.0
    lambda_material: 1.0
  dataset:
    num_layers: 16
    ranges: [400, 700]
    steps: 1  # hpc 0.1
    dataset_size: 1000
    # dataset_size_test: 1000
train:
  num_workers: 16
  save_checkpoints: true
  epochs: 100
  save_every: 2
  clip_max_norm: 1.0
  learning_rate: 0.0001
