general:
  experiment: "opod_tic"
  main_path: "/home/ayman" # "/home/woody/iwnt/iwnt153h"
  dataset: "/mnt/f/images" # "/home/woody/iwnt/iwnt153h/data/images"
  config: "opod_tic"
train:
  dataset:
      num_layers: 20
      ranges: [400, 700]
      steps: 1
      dataset_size: 10000
  seed: 42
  epochs: 200
  learning_rate: 0.0001
  num_workers: 16
  batch_size: 2
  test_batch_size: 2
  aux_learning_rate: 0.001
  patch_size: [256, 256] # [512, 512]
  save: True
  mixed_precision: "fp16" # "bf16" # "fp16"
  clip_max_norm: 1.0
  checkpoint: None
  save_every: 1
  scheduler_type: "cosine_with_cosine_warmup" # Options: "cosine_with_warmup", "cosine_with_cosine_warmup", "cosine_annealing"
  losses:
    lmbda_bpp_loss: 1.0e-2
    lmbda_quantizer_loss: 1.0
    lmbda_perceptual_loss: 1.0
    # lmbda_kl_loss: 1.0e-6
    # discriminator_start: 200000
    # discriminator_factor: 1.0
    # discriminator_weight: 0.1
    # lecam_regularization_weight: 0.001

test: 
  test_dataset: "repos/summary/data/KodakDataset" # "repos/summary/data/professional_valid_2020" 
  batch_size: 1
  checkpoint: "experiments/loclic/loclic"
  output_dir: "repos/summary"
  lmbda: 0.01 # To calculate the loss
  lmbda2: 1 # To calculate the loss
