dataset_params:
  img_path: ''
  img_size: 256
  in_channels: 1

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02


dit_params:
  patch_size : 2
  num_layers : 12
  hidden_size : 768
  num_heads : 12
  head_dim : 64
  timestep_emb_dim : 768
  spectrum_len : 100
  
