# name: SimpleEncoderNextLayer
# hidden_size: 512  # Options: 512 (small), 768 (base), 1024 (large)
# num_layers: 8    # Options: 8 (small), 12 (base), 24 (large)
# num_heads: 8    # Options: 8 (small), 12 (base), 16 (large)
name: SimpleEncoderNextLayer
hidden_size: 768  # Options: 512 (small), 768 (base), 1024 (large)
num_layers: 12    # Options: 8 (small), 12 (base), 24 (large)
num_heads: 12     # Options: 8 (small), 12 (base), 16 (large)
kernel_size: 9
